 [custom]
custom_proxy_group=📹 油管视频`select`[]✈️ 主要节点`[]👍🏻 自建及优质节点`[]👨🏻‍🦽 手动切换`[]🇺🇲🇺🇲 美-美自建落地`[]🇸🇬🇺🇲 新-美自建落地`[]🇭🇰🇺🇲 港-美自建落地`[]🇯🇵🇺🇲 日-美自建落地`[]🇯🇵🇯🇵 日-日自建落地`[]🇭🇰 香港负载均衡`[]🇭🇰 香港测速`[]🇸🇬 新加坡负载均衡`[]🇸🇬 新加坡测速`[]🇺🇲 美国负载均衡`[]🇺🇲 美国测速`[]🇯🇵 日本负载均衡`[]🇯🇵 日本测速`[]🇨🇳 湾湾手选`[]🇰🇷 棒子手选`[]🇹🇷 土耳其手选`[]🇦🇷 阿根廷手选`[]🇬🇧 英国手选`[]🙊 低倍or无版权or特殊流媒体`[]DIRECT

custom_proxy_group=📢 谷歌服务`select`[]✈️ 主要节点`[]👍🏻 自建及优质节点`[]DIRECT`[]👨🏻‍🦽 手动切换`[]🇺🇲🇺🇲 美-美自建落地`[]🇸🇬🇺🇲 新-美自建落地`[]🇭🇰🇺🇲 港-美自建落地`[]🇯🇵🇺🇲 日-美自建落地`[]🇯🇵🇯🇵 日-日自建落地`[]🇭🇰 香港负载均衡`[]🇭🇰 香港测速`[]🇸🇬 新加坡负载均衡`[]🇸🇬 新加坡测速`[]🇺🇲 美国负载均衡`[]🇺🇲 美国测速`[]🇯🇵 日本负载均衡`[]🇯🇵 日本测速`[]🇨🇳 湾湾手选`[]🇰🇷 棒子手选`[]🇹🇷 土耳其手选`[]🇦🇷 阿根廷手选`[]🇬🇧 英国手选`[]🙊 低倍or无版权or特殊流媒体

custom_proxy_group=📜 学术代理`select`[]✈️ 主要节点`[]👍🏻 自建及优质节点`[]DIRECT`[]👨🏻‍🦽 手动切换`[]🇺🇲🇺🇲 美-美自建落地`[]🇸🇬🇺🇲 新-美自建落地`[]🇭🇰🇺🇲 港-美自建落地`[]🇯🇵🇺🇲 日-美自建落地`[]🇯🇵🇯🇵 日-日自建落地`[]🇭🇰 香港负载均衡`[]🇭🇰 香港测速`[]🇸🇬 新加坡负载均衡`[]🇸🇬 新加坡测速`[]🇺🇲 美国负载均衡`[]🇺🇲 美国测速`[]🇯🇵 日本负载均衡`[]🇯🇵 日本测速`[]🇨🇳 湾湾手选`[]🇰🇷 棒子手选`[]🇹🇷 土耳其手选`[]🇦🇷 阿根廷手选`[]🇬🇧 英国手选`[]🙊 低倍or无版权or特殊流媒体

custom_proxy_group=📚 学术直连`select`[]🗞 学术专用网`[]DIRECT`[]✈️ 主要节点`[]👍🏻 自建及优质节点`[]👨🏻‍🦽 手动切换`[]🇺🇲🇺🇲 美-美自建落地`[]🇸🇬🇺🇲 新-美自建落地`[]🇭🇰🇺🇲 港-美自建落地`[]🇯🇵🇺🇲 日-美自建落地`[]🇯🇵🇯🇵 日-日自建落地`[]🇭🇰 香港负载均衡`[]🇭🇰 香港测速`[]🇸🇬 新加坡负载均衡`[]🇸🇬 新加坡测速`[]🇺🇲 美国负载均衡`[]🇺🇲 美国测速`[]🇯🇵 日本负载均衡`[]🇯🇵 日本测速`[]🇨🇳 湾湾手选`[]🇰🇷 棒子手选`[]🇹🇷 土耳其手选`[]🇦🇷 阿根廷手选`[]🇬🇧 英国手选`[]🙊 低倍or无版权or特殊流媒体

custom_proxy_group=📧 邮件特服`select`[]✈️ 主要节点`[]👍🏻 自建及优质节点`[]DIRECT`[]👨🏻‍🦽 手动切换`[]🇺🇲🇺🇲 美-美自建落地`[]🇸🇬🇺🇲 新-美自建落地`[]🇭🇰🇺🇲 港-美自建落地`[]🇯🇵🇺🇲 日-美自建落地`[]🇯🇵🇯🇵 日-日自建落地`[]🇭🇰 香港负载均衡`[]🇭🇰 香港测速`[]🇸🇬 新加坡负载均衡`[]🇸🇬 新加坡测速`[]🇺🇲 美国负载均衡`[]🇺🇲 美国测速`[]🇯🇵 日本负载均衡`[]🇯🇵 日本测速`[]🇨🇳 湾湾手选`[]🇰🇷 棒子手选`[]🇹🇷 土耳其手选`[]🇦🇷 阿根廷手选`[]🇬🇧 英国手选`[]🙊 低倍or无版权or特殊流媒体

custom_proxy_group=🎲 游戏平台`select`[]✈️ 主要节点`[]👍🏻 自建及优质节点`[]DIRECT`[]👨🏻‍🦽 手动切换`[]🇺🇲🇺🇲 美-美自建落地`[]🇸🇬🇺🇲 新-美自建落地`[]🇭🇰🇺🇲 港-美自建落地`[]🇯🇵🇺🇲 日-美自建落地`[]🇯🇵🇯🇵 日-日自建落地`[]🇭🇰 香港负载均衡`[]🇭🇰 香港测速`[]🇸🇬 新加坡负载均衡`[]🇸🇬 新加坡测速`[]🇺🇲 美国负载均衡`[]🇺🇲 美国测速`[]🇯🇵 日本负载均衡`[]🇯🇵 日本测速`[]🇨🇳 湾湾手选`[]🇰🇷 棒子手选`[]🇹🇷 土耳其手选`[]🇦🇷 阿根廷手选`[]🇬🇧 英国手选`[]🙊 低倍or无版权or特殊流媒体

custom_proxy_group=🕹 游戏下载`select`[]DIRECT`[]✈️ 主要节点`[]👍🏻 自建及优质节点`[]👨🏻‍🦽 手动切换`[]🇺🇲🇺🇲 美-美自建落地`[]🇸🇬🇺🇲 新-美自建落地`[]🇭🇰🇺🇲 港-美自建落地`[]🇯🇵🇺🇲 日-美自建落地`[]🇯🇵🇯🇵 日-日自建落地`[]🇭🇰 香港负载均衡`[]🇭🇰 香港测速`[]🇸🇬 新加坡负载均衡`[]🇸🇬 新加坡测速`[]🇺🇲 美国负载均衡`[]🇺🇲 美国测速`[]🇯🇵 日本负载均衡`[]🇯🇵 日本测速`[]🇨🇳 湾湾手选`[]🇰🇷 棒子手选`[]🇹🇷 土耳其手选`[]🇦🇷 阿根廷手选`[]🇬🇧 英国手选`[]🙊 低倍or无版权or特殊流媒体

custom_proxy_group=☁️ 微软云盘`select`[]✈️ 主要节点`[]👍🏻 自建及优质节点`[]DIRECT`[]👨🏻‍🦽 手动切换`[]🇺🇲🇺🇲 美-美自建落地`[]🇸🇬🇺🇲 新-美自建落地`[]🇭🇰🇺🇲 港-美自建落地`[]🇯🇵🇺🇲 日-美自建落地`[]🇯🇵🇯🇵 日-日自建落地`[]🇭🇰 香港负载均衡`[]🇭🇰 香港测速`[]🇸🇬 新加坡负载均衡`[]🇸🇬 新加坡测速`[]🇺🇲 美国负载均衡`[]🇺🇲 美国测速`[]🇯🇵 日本负载均衡`[]🇯🇵 日本测速`[]🇨🇳 湾湾手选`[]🇰🇷 棒子手选`[]🇹🇷 土耳其手选`[]🇦🇷 阿根廷手选`[]🇬🇧 英国手选`[]🙊 低倍or无版权or特殊流媒体

custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]✈️ 主要节点`[]👍🏻 自建及优质节点`[]👨🏻‍🦽 手动切换`[]🇺🇲🇺🇲 美-美自建落地`[]🇸🇬🇺🇲 新-美自建落地`[]🇭🇰🇺🇲 港-美自建落地`[]🇯🇵🇺🇲 日-美自建落地`[]🇯🇵🇯🇵 日-日自建落地`[]🇭🇰 香港负载均衡`[]🇭🇰 香港测速`[]🇸🇬 新加坡负载均衡`[]🇸🇬 新加坡测速`[]🇺🇲 美国负载均衡`[]🇺🇲 美国测速`[]🇯🇵 日本负载均衡`[]🇯🇵 日本测速`[]🇨🇳 湾湾手选`[]🇰🇷 棒子手选`[]🇹🇷 土耳其手选`[]🇦🇷 阿根廷手选`[]🇬🇧 英国手选`[]🙊 低倍or无版权or特殊流媒体

custom_proxy_group=🦅 俄等欧美不友好地区服务`select`[]🇭🇰 香港负载均衡`[]🇰🇷 棒子手选`[]🇹🇷 土耳其手选`[]🇦🇷 阿根廷手选`[]🇭🇰 香港测速`[]✈️ 主要节点`[]👍🏻 自建及优质节点`[]DIRECT`[]👨🏻‍🦽 手动切换`[]🇨🇳 湾湾手选`[]🇸🇬 新加坡测速`[]🇺🇲 美国测速`[]🇸🇬 新加坡负载均衡`[]🇯🇵 日本负载均衡`[]🇺🇲 美国负载均衡`

custom_proxy_group=🌍 国外媒体`select`[]✈️ 主要节点`[]👍🏻 自建及优质节点`[]👨🏻‍🦽 手动切换`[]🇺🇲🇺🇲 美-美自建落地`[]🇸🇬🇺🇲 新-美自建落地`[]🇭🇰🇺🇲 港-美自建落地`[]🇯🇵🇺🇲 日-美自建落地`[]🇯🇵🇯🇵 日-日自建落地`[]🇭🇰 香港负载均衡`[]🇭🇰 香港测速`[]🇸🇬 新加坡负载均衡`[]🇸🇬 新加坡测速`[]🇺🇲 美国负载均衡`[]🇺🇲 美国测速`[]🇯🇵 日本负载均衡`[]🇯🇵 日本测速`[]🇨🇳 湾湾手选`[]🇰🇷 棒子手选`[]🇹🇷 土耳其手选`[]🇦🇷 阿根廷手选`[]🇬🇧 英国手选`[]🙊 低倍or无版权or特殊流媒体`[]DIRECT

custom_proxy_group=⏩ 国内媒体`select`[]DIRECT`[]✈️ 主要节点`[]👍🏻 自建及优质节点`[]👨🏻‍🦽 手动切换`[]🇺🇲🇺🇲 美-美自建落地`[]🇸🇬🇺🇲 新-美自建落地`[]🇭🇰🇺🇲 港-美自建落地`[]🇯🇵🇺🇲 日-美自建落地`[]🇯🇵🇯🇵 日-日自建落地`[]🇭🇰 香港负载均衡`[]🇭🇰 香港测速`[]🇸🇬 新加坡负载均衡`[]🇸🇬 新加坡测速`[]🇺🇲 美国负载均衡`[]🇺🇲 美国测速`[]🇯🇵 日本负载均衡`[]🇯🇵 日本测速`[]🇨🇳 湾湾手选`[]🇰🇷 棒子手选`[]🇹🇷 土耳其手选`[]🇦🇷 阿根廷手选`[]🇬🇧 英国手选`[]🙊 低倍or无版权or特殊流媒体

custom_proxy_group=🍏 苹果全球`select`[]DIRECT`[]✈️ 主要节点`[]👍🏻 自建及优质节点`[]👨🏻‍🦽 手动切换`[]🇺🇲🇺🇲 美-美自建落地`[]🇸🇬🇺🇲 新-美自建落地`[]🇭🇰🇺🇲 港-美自建落地`[]🇯🇵🇺🇲 日-美自建落地`[]🇯🇵🇯🇵 日-日自建落地`[]🇭🇰 香港负载均衡`[]🇭🇰 香港测速`[]🇸🇬 新加坡负载均衡`[]🇸🇬 新加坡测速`[]🇺🇲 美国负载均衡`[]🇺🇲 美国测速`[]🇯🇵 日本负载均衡`[]🇯🇵 日本测速`[]🇨🇳 湾湾手选`[]🇰🇷 棒子手选`[]🇹🇷 土耳其手选`[]🇦🇷 阿根廷手选`[]🇬🇧 英国手选`[]🙊 低倍or无版权or特殊流媒体

custom_proxy_group=📼 哔哩哔哩`select`[]DIRECT`[]✈️ 主要节点`[]👍🏻 自建及优质节点`[]👨🏻‍🦽 手动切换`[]🇭🇰 香港负载均衡`[]🇭🇰 香港测速`[]🇨🇳 湾湾手选`[]🇸🇬 新加坡负载均衡`[]🇸🇬 新加坡测速`[]🇺🇲🇺🇲 美-美自建落地`[]🇸🇬🇺🇲 新-美自建落地`[]🇭🇰🇺🇲 港-美自建落地`[]🇯🇵🇺🇲 日-美自建落地`[]🇯🇵🇯🇵 日-日自建落地`[]🇺🇲 美国负载均衡`[]🇺🇲 美国测速`[]🇯🇵 日本负载均衡`[]🇯🇵 日本测速`[]🇰🇷 棒子手选`[]🇹🇷 土耳其手选`[]🇦🇷 阿根廷手选`[]🇬🇧 英国手选`[]🙊 低倍or无版权or特殊流媒体

custom_proxy_group=🎶 网易音乐`select`[]DIRECT`[]✈️ 主要节点`[]👍🏻 自建及优质节点`[]💠 延迟优先`(网易|音乐|解锁|Music|NetEase)

custom_proxy_group=🎞 奈飞影音`select`[]✈️ 主要节点`[]👍🏻 自建及优质节点`[]👨🏻‍🦽 手动切换`[]🇺🇲🇺🇲 美-美自建落地`[]🇸🇬🇺🇲 新-美自建落地`[]🇭🇰🇺🇲 港-美自建落地`[]🇯🇵🇺🇲 日-美自建落地`[]🇯🇵🇯🇵 日-日自建落地`[]🇭🇰 香港负载均衡`[]🇭🇰 香港测速`[]🇸🇬 新加坡负载均衡`[]🇸🇬 新加坡测速`[]🇺🇲 美国负载均衡`[]🇺🇲 美国测速`[]🇯🇵 日本负载均衡`[]🇯🇵 日本测速`[]🇨🇳 湾湾手选`[]🇰🇷 棒子手选`[]🇹🇷 土耳其手选`[]🇦🇷 阿根廷手选`[]🇬🇧 英国手选`[]🙊 低倍or无版权or特殊流媒体`[]DIRECT

custom_proxy_group=🎧 Spotify`select`[]✈️ 主要节点`[]👍🏻 自建及优质节点`[]👨🏻‍🦽 手动切换`[]🇺🇲🇺🇲 美-美自建落地`[]🇸🇬🇺🇲 新-美自建落地`[]🇭🇰🇺🇲 港-美自建落地`[]🇯🇵🇺🇲 日-美自建落地`[]🇯🇵🇯🇵 日-日自建落地`[]🇭🇰 香港负载均衡`[]🇭🇰 香港测速`[]🇸🇬 新加坡负载均衡`[]🇸🇬 新加坡测速`[]🇺🇲 美国负载均衡`[]🇺🇲 美国测速`[]🇯🇵 日本负载均衡`[]🇯🇵 日本测速`[]🇨🇳 湾湾手选`[]🇰🇷 棒子手选`[]🇹🇷 土耳其手选`[]🇦🇷 阿根廷手选`[]🇬🇧 英国手选`[]🙊 低倍or无版权or特殊流媒体`[]DIRECT

custom_proxy_group=🎬 巴哈姆特`select`[]🇨🇳 湾湾手选`[]✈️ 主要节点`[]👍🏻 自建及优质节点`[]👨🏻‍🦽 手动切换`[]DIRECT

custom_proxy_group=📼 特殊流媒体`select`[]🙊 低倍or无版权or特殊流媒体`[]✈️ 主要节点`[]👍🏻 自建及优质节点`[]👨🏻‍🦽 手动切换`[]🇺🇲🇺🇲 美-美自建落地`[]🇸🇬🇺🇲 新-美自建落地`[]🇭🇰🇺🇲 港-美自建落地`[]🇯🇵🇺🇲 日-美自建落地`[]🇯🇵🇯🇵 日-日自建落地`[]🇭🇰 香港负载均衡`[]🇭🇰 香港测速`[]🇸🇬 新加坡负载均衡`[]🇸🇬 新加坡测速`[]🇺🇲 美国负载均衡`[]🇺🇲 美国测速`[]🇯🇵 日本负载均衡`[]🇯🇵 日本测速`[]🇨🇳 湾湾手选`[]🇰🇷 棒子手选`[]🇹🇷 土耳其手选`[]🇦🇷 阿根廷手选`[]🇬🇧 英国手选`[]DIRECT

custom_proxy_group=🗺️ 全球直连`select`[]DIRECT`[]✈️ 主要节点
custom_proxy_group=🤡 广告与隐私`select`[]DIRECT`[]REJECT`[]✈️ 主要节点`[]👍🏻 自建及优质节点`[]👨🏻‍🦽 手动切换`[]🇺🇲🇺🇲 美-美自建落地`[]🇸🇬🇺🇲 新-美自建落地`[]🇭🇰🇺🇲 港-美自建落地`[]🇯🇵🇺🇲 日-美自建落地`[]🇯🇵🇯🇵 日-日自建落地`[]🇭🇰 香港负载均衡`[]🇭🇰 香港测速`[]🇸🇬 新加坡负载均衡`[]🇸🇬 新加坡测速`[]🇺🇲 美国负载均衡`[]🇺🇲 美国测速`[]🇯🇵 日本负载均衡`[]🇯🇵 日本测速`[]🇨🇳 湾湾手选`[]🇰🇷 棒子手选`[]🇹🇷 土耳其手选`[]🇦🇷 阿根廷手选`[]🇬🇧 英国手选`[]🙊 低倍or无版权or特殊流媒体

custom_proxy_group=🐟 漏网之鱼`select`[]✈️ 主要节点`[]👍🏻 自建及优质节点`[]👨🏻‍🦽 手动切换`[]DIRECT`[]🇺🇲🇺🇲 美-美自建落地`[]🇸🇬🇺🇲 新-美自建落地`[]🇭🇰🇺🇲 港-美自建落地`[]🇯🇵🇺🇲 日-美自建落地`[]🇯🇵🇯🇵 日-日自建落地`[]🇭🇰 香港负载均衡`[]🇭🇰 香港测速`[]🇸🇬 新加坡负载均衡`[]🇸🇬 新加坡测速`[]🇺🇲 美国负载均衡`[]🇺🇲 美国测速`[]🇯🇵 日本负载均衡`[]🇯🇵 日本测速`[]🇨🇳 湾湾手选`[]🇰🇷 棒子手选`[]🇹🇷 土耳其手选`[]🇦🇷 阿根廷手选`[]🇬🇧 英国手选`[]🙊 低倍or无版权or特殊流媒体
; 地区分组列表
custom_proxy_group=👍🏻 自建及优质节点`select`[]👍🏻 美国自建节点`[]👍🏻 新加坡自建节点`[]👍🏻 香港自建节点`[]👍🏻 日本自建节点`[]👍🏻 优质节点
custom_proxy_group=🙊 低倍or无版权or特殊流媒体`select`(LU|卢森堡|低倍|\b0?\.[1-9][\s-]?(?:[xX]|倍)|SP|emby|Emby|EMBY|jellyfin|JELLYFIN|Jellyfin)
custom_proxy_group=🇺🇲🇺🇲 美-美自建落地`relay`[]🇺🇲 美国负载均衡`[]👍🏻 美国自建节点
custom_proxy_group=🇸🇬🇺🇲 新-美自建落地`relay`[]🇸🇬 新加坡负载均衡`[]👍🏻 美国自建节点
custom_proxy_group=🇭🇰🇺🇲 港-美自建落地`relay`[]🇭🇰 香港负载均衡`[]👍🏻 美国自建节点
custom_proxy_group=🇯🇵🇺🇲 日-美自建落地`relay`[]🇯🇵 日本负载均衡`[]👍🏻 美国自建节点
custom_proxy_group=🇯🇵🇯🇵 日-日自建落地`relay`[]🇯🇵 日本负载均衡`[]👍🏻 日本自建节点
custom_proxy_group=🇺🇲 美国测速`url-test`(^(?!.*自建)(?=.*美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|us).+$)`http://detectportal.firefox.com/success.txt`30,,50
custom_proxy_group=🇺🇲 美国负载均衡`load-balance`(^(?!.*自建)(?=.*美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|us).+$)`http://detectportal.firefox.com/success.txt`30,,50
custom_proxy_group=🇸🇬 新加坡测速`url-test`(^(?!.*自建)(?=.*新加坡|坡|狮城|SG|Singapore).+$)`http://detectportal.firefox.com/success.txt`30,500,50
custom_proxy_group=🇸🇬 新加坡负载均衡`load-balance`(^(?!.*自建)(?=.*新加坡|坡|狮城|SG|Singapore).+$)`http://detectportal.firefox.com/success.txt`30,500,50
custom_proxy_group=🇭🇰 香港测速`url-test`(^(?!.*自建)(?=.*港|HK|hk|Hong Kong|HongKong|hongkong).+$)`http://detectportal.firefox.com/success.txt`30,500,50
custom_proxy_group=🇭🇰 香港负载均衡`load-balance`(^(?!.*自建)(?=.*港|HK|hk|Hong Kong|HongKong|hongkong).+$).*`http://detectportal.firefox.com/success.txt`30,500,50
custom_proxy_group=🇯🇵 日本测速`url-test`(^(?!.*自建)(?=.*日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan).+$)`http://detectportal.firefox.com/success.txt`30,500,50
custom_proxy_group=🇯🇵 日本负载均衡`load-balance`(^(?!.*自建)(?=.*日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan).+$)`http://detectportal.firefox.com/success.txt`30,500,50
custom_proxy_group=🇨🇳 湾湾手选`select`(台|新北|彰化|TW|Taiwan)
custom_proxy_group=🇰🇷 棒子手选`select`(KR|Korea|KOR|首尔|韩|韓|南朝)
custom_proxy_group=🇹🇷 土耳其手选`select`(土耳其|Turkey|土区)
custom_proxy_group=🇦🇷 阿根廷手选`select`(阿根廷|Argentina|阿区)
custom_proxy_group=🇬🇧 英国手选`select`(英格兰|UK|GB|英|英国)
custom_proxy_group=🗞 学术专用网`select`(教育|校园|edu|校园内网|学术|文献|论文)
custom_proxy_group=👍🏻 美国自建节点`select`(自建.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|us))
custom_proxy_group=👍🏻 新加坡自建节点`select`(自建.*(新加坡|坡|狮城|SG|Singapore))
custom_proxy_group=👍🏻 香港自建节点`select`(自建.*(港|HK|hk|Hong Kong|HongKong|hongkong))
custom_proxy_group=👍🏻 日本自建节点`select`(自建.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan))
custom_proxy_group=👍🏻 优质节点`select`(优质|精品|IPLC|IPEL|iplc|ipel)
;设置分组标志位

clash_rule_base=https://raw.githubusercontent.com/how1ewu/myclashrule/main/base/ClashBaseRule.yml
enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
