name: blackmatrix7-LLM-update
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "20 */12 * * *"

jobs:
  Update-blackmatrix7-rule:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Download LLM rules
        run: |
          curl -o rules/OpenAI.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
          echo >> rules/OpenAI.list
          curl -o rules/Claude.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.list
          echo >> rules/Claude.list
          curl -o rules/Copilot.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.list
          echo "DOMAIN,designer.microsoft.com" >> rules/Copilot.list
          echo "DOMAIN,edge.microsoft.com" >> rules/Copilot.list
          echo "DOMAIN-SUFFIX,edgeservices.bing.com" >> rules/Copilot.list
          echo "DOMAIN-SUFFIX,bing.com" >> rules/Copilot.list
          echo "DOMAIN-SUFFIX,events.data.microsoft.com" >> rules/Copilot.list
          echo >> rules/Copilot.list
          curl -o rules/BardAI.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BardAI/BardAI.list
          echo >> rules/BardAI.list
          echo "# Gemini" >> rules/Gemini.list
          echo "DOMAIN,ai.google.dev" >> rules/Gemini.list
          echo "DOMAIN,makersuite.google.com" >> rules/Gemini.list
          echo "DOMAIN,generativelanguage.googleapis.com" >> rules/Gemini.list
          echo "DOMAIN,alkalimakersuite-pa.clients6.google.com" >> rules/Gemini.list
          echo "DOMAIN-SUFFIX,bard.google.com" >> rules/Gemini.list
          echo "DOMAIN-SUFFIX,deepmind.com" >> rules/Gemini.list
          echo "DOMAIN-SUFFIX,deepmind.google" >> rules/Gemini.list
          echo "DOMAIN-SUFFIX,generativeai.google" >> rules/Gemini.list
          echo "DOMAIN-SUFFIX,gemini.google.com" >> rules/Gemini.list
          echo "DOMAIN-SUFFIX,proactivebackend-pa.googleapis.com" >> rules/Gemini.list
          echo >> rules/Gemini.list

      - name: Save LLM rules to rules/LLMProxy.list
        run: |
          cat rules/OpenAI.list rules/Claude.list rules/Copilot.list rules/BardAI.list rules/Gemini.list > rules/LLMProxy.list.new
          mv -f rules/LLMProxy.list.new rules/LLMProxy.list
          rm -f rules/OpenAI.list rules/Claude.list rules/Copilot.list rules/BardAI.list rules/Gemini.list

      - name: Add changes to the repository
        run: |
          git add .
          git status

      - name: Commit and push changes
        run: |
          git commit -m "blackmatrix7-LLM-update" -a
          git push
