name: Loyalsoldier-rule-update
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "30 02 * * *"

jobs:
  Update-Loyalsoldier-rule:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Download Telegram rules
        run: |
          curl -o rules/telegramcidr.txt https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt
          echo "" > rules/telegramcidr.list.new
          while IFS= read -r line; 
          do
            ip=$(echo $line | sed "s/  - '//" | sed "s/'//" | sed 's/-//g' | sed "s/'//g"| sed "s/ //g")
            if [[ $ip =~ .*:.* ]]
            then
              # 是IPv6地址，添加"IP-CIDR6,"
              echo "IP-CIDR6,$ip" >> rules/telegramcidr.list.new
            else
              # 是IPv4地址，添加"IP-CIDR,"
              echo "IP-CIDR,$ip" >> rules/telegramcidr.list.new
            fi
          done < <(tail -n +2 rules/telegramcidr.txt)
          mv -f rules/telegramcidr.list.new rules/telegramcidr.list
          sed -i '/^$/d' rules/telegramcidr.list
          rm -f rules/telegramcidr.txt rules/telegramcidr.list.new

      - name: Download DirectDomain rules
        run: |
          curl -o rules/DirectDomain.txt https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt
          echo "" > rules/DirectDomain.list.new
          while IFS= read -r line; 
          do
            domain=$(echo $line | sed "s/  - '//" | sed "s/'//" | sed 's/-//g' | sed "s/'//g" | sed "s/ //g")
            if [[ $domain =~ ^\+\. ]]
            then
              # 去掉 "+." 前缀，并添加 "DOMAIN-SUFFIX,"
              domain=${domain:2}
              echo "DOMAIN-SUFFIX,$domain" >> rules/DirectDomain.list.new
            else
              # 添加 "DOMAIN,"
              echo "DOMAIN,$domain" >> rules/DirectDomain.list.new
            fi
          done < <(tail -n +2 rules/DirectDomain.txt)
          mv -f rules/DirectDomain.list.new rules/DirectDomain.list
          sed -i '/^$/d' rules/DirectDomain.list
          rm -f rules/DirectDomain.txt rules/DirectDomain.list.new

      - name: Download GFWDomain rules
        run: |
          curl -o rules/GFWDomain.txt https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt
          echo "" > rules/GFWDomain.list.new
          while IFS= read -r line; 
          do
            domain=$(echo $line | sed "s/  - '//" | sed "s/'//" | sed 's/-//g' | sed "s/'//g" | sed "s/ //g")
            if [[ $domain =~ ^\+\. ]]
            then
              # 去掉 "+." 前缀，并添加 "DOMAIN-SUFFIX,"
              domain=${domain:2}
              echo "DOMAIN-SUFFIX,$domain" >> rules/GFWDomain.list.new
            else
              # 添加 "DOMAIN,"
              echo "DOMAIN,$domain" >> rules/GFWDomain.list.new
            fi
          done < <(tail -n +2 rules/GFWDomain.txt)
          mv -f rules/GFWDomain.list.new rules/GFWDomain.list
          sed -i '/^$/d' rules/GFWDomain.list
          rm -f rules/GFWDomain.txt rules/GFWDomain.list.new

      - name: Download AppleOrIcloud rules
        run: |
          curl -o rules/APPLE.txt https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt
          echo "" > rules/AppleOrIcloud.list.new
          while IFS= read -r line; 
          do
            domain=$(echo $line | sed "s/  - '//" | sed "s/'//" | sed 's/-//g' | sed "s/'//g" | sed "s/ //g")
            if [[ $domain =~ ^\+\. ]]
            then
              # 去掉 "+." 前缀，并添加 "DOMAIN-SUFFIX,"
              domain=${domain:2}
              echo "DOMAIN-SUFFIX,$domain" >> rules/AppleOrIcloud.list.new
            else
              # 添加 "DOMAIN,"
              echo "DOMAIN,$domain" >> rules/AppleOrIcloud.list.new
            fi
          done < <(tail -n +2 rules/APPLE.txt)
          curl -o rules/ICLOUD.txt https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt
          echo "" > rules/AppleOrIcloud.list.new
          while IFS= read -r line; 
          do
            domain=$(echo $line | sed "s/  - '//" | sed "s/'//" | sed 's/-//g' | sed "s/'//g" | sed "s/ //g")
            if [[ $domain =~ ^\+\. ]]
            then
              # 去掉 "+." 前缀，并添加 "DOMAIN-SUFFIX,"
              domain=${domain:2}
              echo "DOMAIN-SUFFIX,$domain" >> rules/AppleOrIcloud.list.new
            else
              # 添加 "DOMAIN,"
              echo "DOMAIN,$domain" >> rules/AppleOrIcloud.list.new
            fi
          done < <(tail -n +2 rules/ICLOUD.txt)
          mv -f rules/AppleOrIcloud.list.new rules/AppleOrIcloud.list
          sed -i '/^$/d' rules/AppleOrIcloud.list
          rm -f rules/APPLE.txt rules/ICLOUD.txt rules/AppleOrIcloud.list.new

      - name: Download ADDReject rules
        run: |
          curl -o rules/ADDReject.txt https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt
          echo "" > rules/ADDReject.list.new
          while IFS= read -r line; 
          do
            domain=$(echo $line | sed "s/  - '//" | sed "s/'//" | sed 's/-//g' | sed "s/'//g" | sed "s/ //g")
            if [[ $domain =~ ^\+\. ]]
            then
              # 去掉 "+." 前缀，并添加 "DOMAIN-SUFFIX,"
              domain=${domain:2}
              echo "DOMAIN-SUFFIX,$domain" >> rules/ADDReject.list.new
            else
              # 添加 "DOMAIN,"
              echo "DOMAIN,$domain" >> rules/ADDReject.list.new
            fi
          done < <(tail -n +2 rules/ADDReject.txt)
          mv -f rules/ADDReject.list.new rules/ADDReject.list
          sed -i '/^$/d' rules/ADDReject.list
          rm -f rules/ADDReject.txt rules/ADDReject.list.new

      - name: Download MainProxy rules
        run: |
          curl -o rules/MainProxy.txt https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt
          echo "" > rules/MainProxy.list.new
          while IFS= read -r line; 
          do
            domain=$(echo $line | sed "s/  - '//" | sed "s/'//" | sed 's/-//g' | sed "s/'//g" | sed "s/ //g")
            if [[ $domain =~ ^\+\. ]]
            then
              # 去掉 "+." 前缀，并添加 "DOMAIN-SUFFIX,"
              domain=${domain:2}
              echo "DOMAIN-SUFFIX,$domain" >> rules/MainProxy.list.new
            else
              # 添加 "DOMAIN,"
              echo "DOMAIN,$domain" >> rules/MainProxy.list.new
            fi
          done < <(tail -n +2 rules/MainProxy.txt)
          mv -f rules/MainProxy.list.new rules/MainProxy.list
          sed -i '/^$/d' rules/MainProxy.list
          rm -f rules/MainProxy.txt rules/MainProxy.list.new

      - name: Add changes to the repository
        run: |
          git add .
          git status

      - name: Commit and push changes
        run: |
          git commit -m "Loyalsoldier-rule-update" -a
          git push
